export const frenchForbiddenWords = [
  "merde",
  "putain",
  "connard",
  "salope",
  "enculé",
  "négro",
  "baise",
  "bite",
  "chatte",
  "con",
  "couilles",
  "fellation",
  "pédé",
  "PD",
  "pute",
  "sodomie",
  "viol",
  "abruti",
  "crétin",
  "débile",
  "idiot",
  "imbécile",
  "naze",
  "niais",
  "pouffiasse",
  "antisémite",
  "fasciste",
  "hitler",
  "nègre",
  "negro",
  "raciste",
  "terroriste",
];

// Exemple d'utilisation en plus d'une liste de mots, on peut ajouter des phrases ou des expressions (non-recommandé pour ce cas-ci car la base est pour des mots)
export const forbiddenPhrases = ["allez vous faire voir", "va te faire foutre"];
